name: what_to_eat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_common_exports: ^0.1.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

dev_dependencies:
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2

dependency_overrides:
  dartx: ^0.4.1

flutter:
  uses-material-design: true
